version: '3'

services:

  mysql:
    image: mysql:latest
    restart: always
    env_file:
      - mysql.env
    volumes:
      - mysql:/var/lib/mysql

  server:
    image: finnect_backend:${SERVER_VERSION}
    restart: always
    ports:
      - "${SERVER_PORT}:8080"
    env_file:
      - server.env
    depends_on:
      - mysql

volumes:
  mysql: