name: Java CI/CD with Gradle

on:
  push:
    branches: [ "dev" ]
  pull_request_target:
    types: [closed]
    branches: [ "dev" ]

jobs:
  build:
    if: >
      github.event_name == 'push' ||
      (github.event_name == 'pull_request_target' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create .properties file
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.ENV }}" > ./src/main/resources/application.properties

      - name: Decode keystore file
        run: |
          echo ${{ secrets.KEYSTORE_BASE64 }} | base64 --decode > ${{ github.workspace }}/keystore.p12

      - name: Clean project
        run: ./gradlew clean

      - name: Build project excluding tests
        run: ./gradlew build -x test

      - name: Check file
        run: ls ./build/libs/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cicdsample
          path: build/libs/*.jar

  deploy:
    if: needs.build.result == 'success'
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cicdsample

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH server to known hosts
        run: |
          ssh-keygen -R ${{ secrets.SERVER_IP }}
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: SCP transfer and remote script execution
        run: | 
          scp *.jar ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:~/cicd
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "sh serverScript.sh"
